# Generated by Django 5.2.1 on 2025-05-19 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the chat room', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When the room was created')),
                ('members', models.JSONField(blank=True, default=list, help_text='List of chat rooms with name and id')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-created_at'],
            },
        ),
    ]
