# Generated by Django 5.2.1 on 2025-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.JSONField(blank=True, default=list, help_text="List of messages in the format [{'sender': name, 'time_sent': timestamp, 'message': text}]"),
        ),
    ]
